# Generated by Django 5.2.5 on 2025-08-22 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conver_page_image', models.ImageField(upload_to='cover_page_image/')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('revision_number', models.CharField(blank=True, max_length=50, null=True)),
                ('published_date', models.DateField()),
                ('publisher', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('checked_out_date', models.DateTimeField(blank=True, null=True)),
                ('expected_check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_books', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
