# Generated by Django 5.2.5 on 2025-08-22 22:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
