# Generated by Django 5.2.5 on 2025-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[('librarian', 'Librarian'), ('reader', 'Reader')], null=True),
        ),
    ]
