# Generated by Django 5.2.5 on 2025-08-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('librarian', 'Librarian'), ('reader', 'Reader')], null=True),
        ),
    ]
