# Generated by Django 5.2.5 on 2025-08-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-first_name'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
