# Generated by Django 5.2.5 on 2025-08-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('librarian', 'Librarian'), ('reader', 'Reader')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
